version: '3'
services:
  db:
    image: postgres:10 # same version as on heroku
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moving
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/snapshots:/var/lib/postgresql/snapshots
    expose:
      - '5432'

  frontend:
    build:
      context: ./frontend
    ports:
      - '0.0.0.0:7000:3000'
    environment:
      NODE_ENV: 'development'
    volumes:
      - './frontend/:/app/'
      - '/app/node_modules'
