version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '0.0.0.0:7000:3000'
    volumes:
      - './frontend/:/app/'
      - '/app/node_modules'

  backend:
    build:
      context: ./backend
    ports:
      - '0.0.0.0:7100:8000'
    volumes:
      - './backend/:/app/'
